services:
  wb.dev:
    build:
      context: app
    ports:
      - "80:80"
    volumes:
      - "./app/src:/usr/src/public_html/src"
    environment:
      - valkey=wb.valkey.test
      - search=wb.search.test:9200
      - ADMIN_TOKEN=development
      - CLIENT_NS=si_dev
      - WEBHOOK_NS=wh_dev

  wb.test:
    build:
      context: app
    ports:
      - "81:80"
    volumes:
      - "./app/src:/usr/src/public_html/src"
    environment:
        - valkey=wb.valkey.test
        - search=wb.search.test:9200
        - ADMIN_TOKEN=test
        - CLIENT_NS=si_test
        - WEBHOOK_NS=wh_test

  wb.valkey.test:
    build:
      context: cache
    ports:
      - "6379:6379"
    volumes:
      - "./cache/src:/usr/src/public_html/src"

  wb.search.test:
    build:
      context: search
    ports:
      - "9200:9200"
    volumes:
      - "./search/src:/usr/src/public_html/src"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
